#: import ContentNavigationDrawer libs.uix.baseclass.content_nav_drawer.ContentNavigationDrawer

<HomeScreen>

    MDBoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: "Nav-Drawer Activity"
            left_action_items: [["menu", lambda x: nav_drawer.set_state()]]
            right_action_items: [["dots-vertical", lambda x: x]]

        Widget:

    MDNavigationLayout:

        ContentNavigationDrawer:
            id: nav_drawer
